import * as vscode from "vscode";

/**
 * Scaffold the module sub‑folders and files (Odoo 19)
 */
export async function createOdooScaffold(rootUri: vscode.Uri, moduleName: string, type: string): Promise<void> {
    const displayName = moduleName
        .split("_")
        .map((w) => w[0].toUpperCase() + w.slice(1))
        .join(" ");
    if (type == 'basic') {
        const folders = ['models', 'views', 'security'];

        const manifestContent = `# -*- coding: utf-8 -*-
{
    "name": "${displayName}",
    "version": "20.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "This is an autogenerated module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base"],
    "data": [
    "security/ir.access.csv",
    "views/${moduleName}_views.xml"
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}`;

        const modelName = moduleName.replace(/_/g, '.'); // e.g., my_module → my.module
        const formattedModelName = modelName.replace(/\./g, '_')
        const modelPy = `# -*- coding: utf-8 -*-
from odoo import api,fields,models

class ${moduleName
                .split("_")
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join("")}(models.Model):
    _name = '${modelName}'
    _description = '${displayName}'

    name = fields.Char(string="Name", required=True)
    state = fields.Selection([('draft', 'Draft'),('confirmed', 'Confirmed'),('done', 'Done')],
     default='draft', string="State")
    description = fields.Text(string="Description")
    amount = fields.Float(string="Amount")
    active = fields.Boolean(default=True)

    @api.model_create_multi
    def create(self, vals_list):
        """
        Override the create method to assign a sequence-generated name 
        to each record being created.

        :param vals_list: List of dictionaries with field values for new records.
        :return: Recordset of newly created records.
        """
        return super().create(vals_list)

    def write(self, vals):
        """
        Override the write method to include custom behavior when updating records.

        :param vals: Dictionary of field values to update.
        :return: True if the write was successful.
        """
        return super().write(vals)

    def unlink(self):
        """
        Override the unlink method to include custom behavior when deleting records.

        :return: True if the records were successfully deleted.
        """
        return super().unlink()

    def action_do_something(self):
        self.ensure_one()
        # Placeholder for button action
        pass
    `;

        const viewXml = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <record id="${formattedModelName}_view_list" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.list</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <list>
                <field name="name"/>
                <field name="state"/>
                <field name="amount"/>
            </list>
        </field>
    </record>
    <record id="${formattedModelName}_view_form" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.form</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <form string="Form">
                <header>
                    <button name="action_do_something" type="object" string="Do Something" class="oe_highlight"/>
                </header>
                <sheet>
                    <group>
                        <field name="name"/>
                        <field name="state"/>
                        <field name="description"/>
                        <field name="amount"/>
                        <field name="active"/>
                    </group>
                </sheet>
            </form>
        </field>
    </record>
    <record id="${formattedModelName}_view_kanban" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.kanban</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <kanban>
                <templates>
                    <t t-name="card">
                        <field name="name" class="fw-bold fs-5"/>
                        <field name="state" widget="badge"/>
                    </t>
                </templates>
            </kanban>
        </field>
    </record>
    <record id="${formattedModelName}_view_search" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.search</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <search>
                <field name="name"/>
                <field name="state"/>
                <filter string="Active" name="active" domain="[('active','=',True)]"/>
            </search>
        </field>
    </record>
    <record id="action_${formattedModelName}" model="ir.actions.act_window">
        <field name="name">${displayName}</field>
        <field name="res_model">${modelName}</field>
        <field name="view_mode">list,form,kanban</field>
    </record>
    <menuitem id="menu_${formattedModelName}_root" name="${displayName}"/>
    <menuitem id="menu_${moduleName}_main" name="Records" parent="menu_${moduleName}_root" action="action_${formattedModelName}"/>
</odoo>`;

        const accessCsv = `id,name,model_id,group_id/id,operation,domain
access_${formattedModelName}_user,${modelName} user,${modelName},base.group_user,crud,
`;

        const files = {
            "__init__.py":
                `# -*- coding: utf-8 -*-
from . import models`,
            "__manifest__.py": manifestContent,
            "models/__init__.py":
                `# -*- coding: utf-8 -*-
from . import ${formattedModelName}`,
            [`models/${formattedModelName}.py`]: modelPy,
            [`views/${formattedModelName}_views.xml`]: viewXml,
            "security/ir.access.csv": accessCsv,
        };

        // Create all directories
        const dirPromises = folders.map(dir =>
            vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(rootUri, dir))
        );

        // Create all files
        const filePromises = Object.entries(files).map(([relPath, content]) => {
            const fileUri = vscode.Uri.joinPath(rootUri, relPath);
            const uint8arr = Buffer.from(content, 'utf8');
            return vscode.workspace.fs.writeFile(fileUri, uint8arr);
        });

        await Promise.all([...dirPromises, ...filePromises]);
    } else if (type == 'advanced') {
        const folders = ['models', 'views', 'security', 'data', 'demo'];

        const manifestContent = `# -*- coding: utf-8 -*-
{
    "name": "${displayName}",
    "version": "20.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated advanced module",
    "description": "This is an autogenerated advanced module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base"],
    "data": [
        "security/ir.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "views/${moduleName}_views.xml"
    ],
    "demo": [
        "demo/${moduleName}_data.xml"
    ],
    "assets": {},
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}`;

        const modelName = moduleName.replace(/_/g, '.');
        const formattedModelName = modelName.replace(/\./g, '_');

        const modelPy = `# -*- coding: utf-8 -*-
from datetime import datetime
from odoo import api,fields,models,_

class ${moduleName
                .split("_")
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join("")}(models.Model):
    _name = '${modelName}'
    _description = '${displayName}'

    name = fields.Char(string="Name", default=lambda self: _('New'), readonly=True, copy=False,)
    state = fields.Selection([('draft', 'Draft'),('confirmed', 'Confirmed'),('done', 'Done')],
     default='draft', string="State")
    description = fields.Text(string="Description")
    amount = fields.Float(string="Amount")
    active = fields.Boolean(default=True)
    date = fields.Date(string="Date", default=fields.Date.context_today)

    @api.model_create_multi
    def create(self, vals_list):
        """
        Override the create method to assign a sequence-generated name 
        to each record being created.

        :param vals_list: List of dictionaries with field values for new records.
        :return: Recordset of newly created records.
        """
        for vals in vals_list:
            sequence = self.env['ir.sequence'].next_by_code('${formattedModelName}')
            vals['name'] = sequence or _('New')
        return super().create(vals_list)

    def write(self, vals):
        """
        Override the write method to include custom behavior when updating records.

        :param vals: Dictionary of field values to update.
        :return: True if the write was successful.
        """
        return super().write(vals)

    def unlink(self):
        """
        Override the unlink method to include custom behavior when deleting records.

        :return: True if the records were successfully deleted.
        """
        return super().unlink()

    def action_do_something(self):
        self.ensure_one()
        # Placeholder for button action
        pass

    def cron_sample_method(self):
        # Placeholder for scheduled action
        pass
`;

        const viewXml = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <!-- List View -->
    <record id="${formattedModelName}_view_list" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.list</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <list>
                <field name="name"/>
                <field name="state"/>
                <field name="amount"/>
                <field name="date"/>
            </list>
        </field>
    </record>

    <!-- Form View -->
    <record id="${formattedModelName}_view_form" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.form</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <form string="Form">
                <header>
                    <button name="action_do_something" type="object" string="Do Something" class="oe_highlight"/>
                </header>
                <sheet>
                    <group>
                        <field name="name"/>
                        <field name="state"/>
                        <field name="description"/>
                        <field name="amount"/>
                        <field name="date"/>
                        <field name="active"/>
                    </group>
                </sheet>
            </form>
        </field>
    </record>

    <!-- Kanban View -->
    <record id="${formattedModelName}_view_kanban" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.kanban</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <kanban>
                <templates>
                    <t t-name="card">
                        <field name="name" class="fw-bold fs-5"/>
                        <field name="state" widget="badge"/>
                    </t>
                </templates>
            </kanban>
        </field>
    </record>

    <!-- Calendar View -->
    <record id="${formattedModelName}_view_calendar" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.calendar</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <calendar string="Calendar" date_start="date">
                <field name="name"/>
            </calendar>
        </field>
    </record>

    <!-- Pivot View -->
    <record id="${formattedModelName}_view_pivot" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.pivot</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <pivot>
                <field name="state"/>
                <field name="amount"/>
            </pivot>
        </field>
    </record>

    <!-- Search View -->
    <record id="${formattedModelName}_view_search" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.search</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <search>
                <field name="name"/>
                <field name="state"/>
                <filter string="Draft" name="state" domain="[('state','=','draft')]"/>
                <filter string="Active" name="active" domain="[('active','=',True)]"/>
            </search>
        </field>
    </record>

    <!-- Action -->
    <record id="action_${formattedModelName}" model="ir.actions.act_window">
        <field name="name">${displayName}</field>
        <field name="res_model">${modelName}</field>
        <field name="view_mode">list,form,kanban,calendar,pivot</field>
    </record>

    <!-- Menu -->
    <menuitem id="menu_${formattedModelName}_root" name="${displayName}"/>
    <menuitem id="menu_${formattedModelName}_main" name="Records" parent="menu_${formattedModelName}_root" action="action_${formattedModelName}"/>
</odoo>
`;

        const accessCsv = `id,name,model_id,group_id/id,operation,domain
access_${formattedModelName}_user,${modelName} user,${modelName},base.group_user,crud,
`;
        const dataXml = `<?xml version="1.0" encoding="utf-8"?>
<odoo noupdate="1">
    <record id="${formattedModelName}_demo_data_1" model="${modelName}">
        <field name="state">draft</field>
        <field name="description">Demo Description</field>
        
    </record>
    <record id="${formattedModelName}_demo_data_2" model="${modelName}">
        <field name="state">confirmed</field>
        <field name="description">Demo Description</field>
    </record>
</odoo>
`;

        const sequenceXml = `<?xml version="1.0" encoding="utf-8"?>
<odoo noupdate="1">
    <record id="ir_sequence_${formattedModelName}" model="ir.sequence">
        <field name="name">${moduleName} Sequence</field>
        <field name="code">${formattedModelName}</field>
        <field name="prefix">SEQ</field>
        <field name="padding">5</field>
        <field name="number_next">1</field>
        <field name="number_increment">1</field>
        <field name="company_id" eval="False"/>
    </record>
</odoo>
`;

        const cronXml = `<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="ir_cron_${formattedModelName}" model="ir.cron">
        <field name="name">${moduleName} Scheduled Action</field>
        <field name="model_id" ref="model_${formattedModelName}"/>
        <field name="state">code</field>
        <field name="code">model.cron_sample_method()</field>
        <field name="interval_number">1</field>
        <field name="interval_type">days</field>
        <field name="active">True</field>
    </record>
</odoo>
`;

        const files = {
            "__init__.py":
                `# -*- coding: utf-8 -*-
from . import models`,
            "__manifest__.py": manifestContent,
            "models/__init__.py":
                `# -*- coding: utf-8 -*-
from . import ${formattedModelName}`,
            [`models/${formattedModelName}.py`]: modelPy,
            [`views/${formattedModelName}_views.xml`]: viewXml,
            "security/ir.access.csv": accessCsv,
            "data/ir_sequence_data.xml": sequenceXml,
            [`demo/${moduleName}_data.xml`]: dataXml,
            "data/ir_cron_data.xml": cronXml,
        };

        const dirPromises = folders.map(dir =>
            vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(rootUri, dir))
        );

        const filePromises = Object.entries(files).map(([relPath, content]) => {
            const fileUri = vscode.Uri.joinPath(rootUri, relPath);
            const uint8arr = Buffer.from(content, 'utf8');
            return vscode.workspace.fs.writeFile(fileUri, uint8arr);
        });

        await Promise.all([...dirPromises, ...filePromises]);
    } else if (type == 'owl_basic') {
        const folders = ['models', 'views', 'security', 'static/src/js', 'static/src/xml'];

        const manifestContent = `# -*- coding: utf-8 -*-
{
    "name": "${displayName}",
    "version": "20.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated OWL module",
    "description": "This is an autogenerated OWL module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["base", "web"],
    "data": [
        "security/ir.access.csv",
        "views/${moduleName}_views.xml"
    ],
    "assets": {
        "web.assets_backend": [
            "${moduleName}/static/src/js/client_action.js",
            "${moduleName}/static/src/xml/client_action.xml"
        ]
    },
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}`;

        const modelName = moduleName.replace(/_/g, '.');
        const formattedModelName = modelName.replace(/\./g, '_');
        const modelClassName = moduleName.replace(/_/g, '').replace(/\b\w/g, l => l.toUpperCase());

        const modelPy = `# -*- coding: utf-8 -*-
from odoo import api,fields,models

class ${moduleName
                .split("_")
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join("")}(models.Model):
    _name = '${modelName}'
    _description = '${displayName}'

    name = fields.Char(string="Name", required=True)
    state = fields.Selection([('draft', 'Draft'),('confirmed', 'Confirmed'),('done', 'Done')],
        default='draft', string="State")
    description = fields.Text(string="Description")
    amount = fields.Float(string="Amount")
    active = fields.Boolean(default=True)

    def action_do_something(self):
        self.ensure_one()
        return {
            'type': 'ir.actions.client',
            'tag': '${moduleName}.${moduleName}',
            'params': {
                'model': self._name,
                'id': self.id,
            }
        }
`;

        const viewXml = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <record id="${formattedModelName}_view_list" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.list</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <list>
                <field name="name"/>
                <field name="state"/>
                <field name="amount"/>
            </list>
        </field>
    </record>
    <record id="${formattedModelName}_view_form" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.form</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <form string="Form">
                <header>
                    <button name="action_do_something" type="object" string="Open OWL View" class="oe_highlight"/>
                </header>
                <sheet>
                    <group>
                        <field name="name"/>
                        <field name="state"/>
                        <field name="description"/>
                        <field name="amount"/>
                        <field name="active"/>
                    </group>
                </sheet>
            </form>
        </field>
    </record>
    <record id="action_${formattedModelName}" model="ir.actions.act_window">
        <field name="name">${displayName}</field>
        <field name="res_model">${modelName}</field>
        <field name="view_mode">list,form</field>
    </record>
    <menuitem id="menu_${formattedModelName}_root" name="${displayName}"/>
    <menuitem id="menu_${formattedModelName}_main" name="Records" parent="menu_${formattedModelName}_root" action="action_${formattedModelName}"/>
</odoo>`;

        const accessCsv = `id,name,model_id,group_id/id,operation,domain
access_${formattedModelName}_user,${modelName} user,${modelName},base.group_user,crud,
`;

        const clientAction = `import { Component } from "@odoo/owl";
import { registry } from "@web/core/registry";
import { useService } from "@web/core/utils/hooks";

/** Client action "${moduleName}.${moduleName}", opened by the menu of this module. */
export class ${modelClassName} extends Component {
    static template = "${moduleName}.${modelClassName}";

    setup() {
        this.orm = useService("orm");
        this.notification = useService("notification");
    }

    onClickHello() {
        this.notification.add("Hello from ${moduleName}!", { type: "success" });
    }
}

registry.category("actions").add("${moduleName}.${moduleName}", ${modelClassName});
`;

        const clientActionTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">
    <t t-name="${moduleName}.${modelClassName}">
        <div class="o_action container mt-3">
            <h1 class="text-center text-primary">Welcome Screen</h1>
            <div class="text-center mt-3">
                <button class="btn btn-primary" t-on-click="() => this.onClickHello()">Say hello</button>
            </div>
        </div>
    </t>
</templates>`;

        const files = {
            "__init__.py":
                `# -*- coding: utf-8 -*-
from . import models`,
            "__manifest__.py": manifestContent,
            "models/__init__.py":
                `# -*- coding: utf-8 -*-
from . import ${formattedModelName}`,
            [`models/${formattedModelName}.py`]: modelPy,
            [`views/${formattedModelName}_views.xml`]: viewXml,
            "security/ir.access.csv": accessCsv,
            ["static/src/js/client_action.js"]: clientAction,
            ["static/src/xml/client_action.xml"]: clientActionTemplate,
        };

        const dirPromises = folders.map(dir =>
            vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(rootUri, dir))
        );

        const filePromises = Object.entries(files).map(([relPath, content]) => {
            const fileUri = vscode.Uri.joinPath(rootUri, relPath);
            const uint8arr = Buffer.from(content, 'utf8');
            return vscode.workspace.fs.writeFile(fileUri, uint8arr);
        });

        await Promise.all([...dirPromises, ...filePromises]);
    } else if (type == 'owl_advanced') {
        const folders = ['models', 'views', 'security', 'data', 'demo', 'static', 'controllers'];

        const manifestContent = `# -*- coding: utf-8 -*-
{
    "name": "${displayName}",
    "version": "20.0.1.0.0",
    "category": "Tools",
    "summary": "",
    "description": "",
    "author": "",
    "maintainer": "",
    "website": "",
    "depends": ["base", "mail", "contacts"],
    "data": [
        "security/ir.access.csv",
        "data/ir_sequence_data.xml",
        "data/ir_cron_data.xml",
        "views/${moduleName}_views.xml"
    ],
    "demo": [
        "demo/${moduleName}_data.xml"
    ],
    "assets": {
        'web.assets_backend': [
            '${moduleName}/static/src/js/client_action.js',
            '${moduleName}/static/src/xml/client_action.xml',
            '${moduleName}/static/src/scss/client_action.scss',
        ]
    },
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
}`;

        const modelName = moduleName.replace(/_/g, '.');
        const formattedModelName = modelName.replace(/\./g, '_');

        const modelClassName = moduleName.replace(/_/g, '').replace(/\b\w/g, l => l.toUpperCase());
        const controllerPy = `# -*- coding: utf-8 -*-
from odoo import http
from odoo.http import request


class ${modelClassName}Dashboard(http.Controller):

    @http.route('/${moduleName}/chart_data', type='jsonrpc', auth='user')
    def chart_data(self, date=None):
        """Totals per partner for the dashboard charts (optionally for one date)."""
        domain = [('date', '=', date)] if date else []
        groups = request.env['${modelName}']._read_group(domain, ['partner_id'], ['__count', 'amount:sum'])
        return [{
            'partner': partner.display_name,
            'total_records': count,
            'total_amount': amount,
        } for partner, count, amount in groups]
`;

        const modelPy = `# -*- coding: utf-8 -*-
from datetime import datetime
from odoo import models, fields, api, _

class ${moduleName
                .split("_")
                .map((word) => word.charAt(0).toUpperCase() + word.slice(1))
                .join("")}(models.Model):
    _name = '${modelName}'
    _description = '${displayName}'
    _inherit = ['mail.thread']

    name = fields.Char(string="Name", default=lambda self: _('New'), readonly=True, copy=False,)
    state = fields.Selection([
        ('draft', 'Draft'),
        ('confirmed', 'Confirmed'),
        ('done', 'Done')
    ], default='draft', string="State")
    description = fields.Text(string="Description")
    amount = fields.Float(string="Amount")
    active = fields.Boolean(default=True)
    date = fields.Date(string="Date", default=fields.Date.context_today)
    company_id = fields.Many2one(comodel_name='res.company', string='Company',
                                 default=lambda self: self.env.company)
    partner_id = fields.Many2one(comodel_name='res.partner', string='Partner', required=True)
    user_id = fields.Many2one(
        comodel_name='res.users',
        string='User',
        default=lambda self: self.env.user,
    )



    @api.model_create_multi
    def create(self, vals_list):
        """
        Override the create method to assign a sequence-generated name 
        to each record being created.

        :param vals_list: List of dictionaries with field values for new records.
        :return: Recordset of newly created records.
        """
        for vals in vals_list:
            sequence = self.env['ir.sequence'].next_by_code('${formattedModelName}')
            vals['name'] = sequence or _('New')
        return super().create(vals_list)

    def write(self, vals):
        """
        Override the write method to include custom behavior when updating records.

        :param vals: Dictionary of field values to update.
        :return: True if the write was successful.
        """
        return super().write(vals)

    def unlink(self):
        """
        Override the unlink method to include custom behavior when deleting records.

        :return: True if the records were successfully deleted.
        """
        return super().unlink()

    def action_do_something(self):
        self.ensure_one()
        # Placeholder for button action
        pass

    def cron_sample_method(self):
        # Placeholder for scheduled action
        pass
`;

        const viewXml = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <!-- List View -->
    <record id="${formattedModelName}_view_list" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.list</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <list>
                <field name="name"/>
                <field name="state"/>
                <field name="amount"/>
                <field name="date"/>
            </list>
        </field>
    </record>

    <!-- Form View -->
    <record id="${formattedModelName}_view_form" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.form</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <form string="Form">
                <header>
                    <button name="action_do_something" type="object" string="Do Something" class="oe_highlight"/>
                    <field name="state" widget="statusbar"/>
                </header>
                <sheet>
                    <div class="oe_title">
                        <label for="name"/>
                        <h1>
                            <field name="name"/>
                        </h1>
                    </div>
                    <group>
                        <group>
                            <field name="partner_id"/>
                            <field name="amount"/>
                            <field name="date"/>
                        </group>
                        <group>
                            <field name="company_id"/>
                            <field name="description"/>
                        </group>

                        <field name="active" invisible="1"/>
                    </group>
                </sheet>
                 <chatter/>
            </form>

        </field>
    </record>

    <!-- Kanban View -->
    <record id="${formattedModelName}_view_kanban" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.kanban</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <kanban>
                <templates>
                    <t t-name="card">
                        <field name="name" class="fw-bold fs-5"/>
                        <field name="state" widget="badge"/>
                    </t>
                </templates>
            </kanban>
        </field>
    </record>

    <!-- Calendar View -->
    <record id="${formattedModelName}_view_calendar" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.calendar</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <calendar string="Calendar" date_start="date">
                <field name="name"/>
            </calendar>
        </field>
    </record>

    <!-- Pivot View -->
    <record id="${formattedModelName}_view_pivot" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.pivot</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <pivot>
                <field name="state"/>
                <field name="amount"/>
            </pivot>
        </field>
    </record>

    <!-- Search View -->
    <record id="${formattedModelName}_view_search" model="ir.ui.view">
        <field name="name">${formattedModelName}.view.search</field>
        <field name="model">${modelName}</field>
        <field name="arch" type="xml">
            <search>
                <field name="name"/>
                <field name="state"/>
                <filter string="Draft" name="state" domain="[('state','=','draft')]"/>
                <filter string="Active" name="active" domain="[('active','=',True)]"/>
            </search>
        </field>
    </record>

    <!-- Action -->
    <record id="action_${formattedModelName}" model="ir.actions.act_window">
        <field name="name">${displayName}</field>
        <field name="res_model">${modelName}</field>
        <field name="view_mode">list,form,kanban,calendar,pivot</field>
    </record>

    <!-- Client Action -->
    <record id="${moduleName}_action" model="ir.actions.client">
            <field name="name">Client Action</field>
            <field name="tag">${moduleName}.${moduleName}</field>
    </record>
    <menuitem id="menu_${formattedModelName}_root" name="${moduleName}" action="${moduleName}_action"/>

    <!-- Menu -->
    <menuitem id="menu_${formattedModelName}_root" name="${displayName}"/>
    <menuitem id="menu_${formattedModelName}_main" name="Records" parent="menu_${formattedModelName}_root" action="action_${formattedModelName}"/>
</odoo>
`;

        const accessCsv = `id,name,model_id,group_id/id,operation,domain
access_${formattedModelName}_user,${modelName} user,${modelName},base.group_user,crud,
`;
        const dataXml = `<?xml version="1.0" encoding="utf-8"?>
<odoo noupdate="1">
    <record id="${formattedModelName}_demo_data_1" model="${modelName}">
        <field name="state">draft</field>
        <field name="description">Demo Description</field>
        <field name="partner_id" ref="base.res_partner_1"/>
        <field name="amount">100</field>
    </record>
    <record id="${formattedModelName}_demo_data_2" model="${modelName}">
        <field name="state">confirmed</field>
        <field name="description">Demo Description</field>
        <field name="partner_id" ref="base.res_partner_2"/>
        <field name="amount">200</field>
    </record>
    <record id="${formattedModelName}_demo_data_3" model="${modelName}">
        <field name="state">confirmed</field>
        <field name="description">Demo Description</field>
        <field name="partner_id" ref="base.res_partner_3"/>
        <field name="amount">10</field>
    </record>
</odoo>
    `;

        const sequenceXml = `<?xml version="1.0" encoding="utf-8"?>
<odoo noupdate="1">
    <record id="ir_sequence_${formattedModelName}" model="ir.sequence">
        <field name="name">${moduleName} Sequence</field>
        <field name="code">${formattedModelName}</field>
        <field name="prefix">SEQ</field>
        <field name="padding">5</field>
        <field name="number_next">1</field>
        <field name="number_increment">1</field>
        <field name="company_id" eval="False"/>
    </record>
</odoo>
`;

        const cronXml = `<?xml version="1.0" encoding="utf-8"?>
<odoo>
    <record id="ir_cron_${formattedModelName}" model="ir.cron">
        <field name="name">${moduleName} Scheduled Action</field>
        <field name="model_id" ref="model_${formattedModelName}"/>
        <field name="state">code</field>
        <field name="code">model.cron_sample_method()</field>
        <field name="interval_number">1</field>
        <field name="interval_type">days</field>
        <field name="active">True</field>
    </record>
</odoo>
`;
        const clientAction = `import { Component, onWillStart, proxy, signal } from "@odoo/owl";
import { useLayoutEffect } from "@web/owl2/utils";
import { registry } from "@web/core/registry";
import { useService } from "@web/core/utils/hooks";
import { loadBundle } from "@web/core/assets";
import { rpc } from "@web/core/network/rpc";

const CHART_TYPES = {
    pie_chart: "pie",
    donut_chart: "doughnut",
    bar_chart: "bar",
    line_chart: "line",
};

/** Dashboard client action "${moduleName}.${moduleName}" (Odoo 20 / Owl 3, Chart.js bundled by Odoo). */
export class ${modelClassName} extends Component {
    static template = "${moduleName}.${modelClassName}";

    state = proxy({
        records: [],
        selectedRecord: null,
        date: "",
        chartType: "",
    });
    canvas = signal.ref();

    setup() {
        this.orm = useService("orm");
        this.chart = null;
        onWillStart(async () => {
            await loadBundle("web.chartjs_lib");
            this.state.records = await this.orm.searchRead(
                "${modelName}",
                [],
                ["name", "state", "description", "active", "date", "amount", "partner_id", "user_id"],
                { context: { active_test: false } }
            );
        });
        // Redraw when the chart type or the date filter changes
        useLayoutEffect(
            () => {
                this.renderChart();
                return () => this.chart?.destroy();
            },
            () => [this.state.chartType, this.state.date]
        );
    }

    async renderChart() {
        this.chart?.destroy();
        this.chart = null;
        const type = CHART_TYPES[this.state.chartType];
        if (!type || !this.canvas()) {
            return;
        }
        const data = await rpc("/${moduleName}/chart_data", { date: this.state.date || null });
        this.chart = new Chart(this.canvas(), {
            type,
            data: {
                labels: data.map((item) => item.partner),
                datasets: [{
                    label: "Amount",
                    data: data.map((item) => item.total_amount),
                }],
            },
            options: { responsive: true, maintainAspectRatio: false },
        });
    }

    onSelectRecord(ev) {
        const id = parseInt(ev.target.value, 10);
        this.state.selectedRecord = this.state.records.find((record) => record.id === id) || null;
    }

    onSelectChart(ev) {
        this.state.chartType = ev.target.value;
    }

    onChangeDate(ev) {
        this.state.date = ev.target.value;
    }
}

registry.category("actions").add("${moduleName}.${moduleName}", ${modelClassName});
`;

        const clientActionTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<templates xml:space="preserve">
    <t t-name="${moduleName}.${modelClassName}">
        <div class="o_action o_${moduleName}_dashboard container-fluid p-4 overflow-auto">
            <h1 class="mb-4">${displayName} Dashboard</h1>
            <div class="row g-3 mb-4">
                <div class="col-md-4">
                    <label class="form-label" for="${moduleName}_record">Record</label>
                    <select id="${moduleName}_record" class="form-select" t-on-change="(ev) => this.onSelectRecord(ev)">
                        <option value="">Select a record</option>
                        <option t-foreach="this.state.records" t-as="record" t-key="record.id"
                                t-att-value="record.id" t-att-selected="record.id === this.state.selectedRecord?.id"
                                t-out="record.name"/>
                    </select>
                </div>
                <div class="col-md-4">
                    <label class="form-label" for="${moduleName}_chart">Chart</label>
                    <select id="${moduleName}_chart" class="form-select" t-on-change="(ev) => this.onSelectChart(ev)">
                        <option value="">Select a chart</option>
                        <option value="pie_chart">Pie</option>
                        <option value="donut_chart">Donut</option>
                        <option value="bar_chart">Bar</option>
                        <option value="line_chart">Line</option>
                    </select>
                </div>
                <div class="col-md-4">
                    <label class="form-label" for="${moduleName}_date">Date</label>
                    <input id="${moduleName}_date" type="date" class="form-control" t-on-change="(ev) => this.onChangeDate(ev)"/>
                </div>
            </div>

            <div t-if="this.state.selectedRecord" class="card mb-4">
                <div class="card-header fw-bold" t-out="this.state.selectedRecord.name"/>
                <table class="table mb-0">
                    <tbody>
                        <tr><th>Status</th><td t-out="this.state.selectedRecord.state"/></tr>
                        <tr><th>Partner</th><td t-out="this.state.selectedRecord.partner_id?.[1] or ''"/></tr>
                        <tr><th>Date</th><td t-out="this.state.selectedRecord.date or ''"/></tr>
                        <tr><th>Amount</th><td t-out="this.state.selectedRecord.amount"/></tr>
                        <tr><th>Description</th><td t-out="this.state.selectedRecord.description or ''"/></tr>
                    </tbody>
                </table>
            </div>

            <div t-if="this.state.chartType" class="card">
                <div class="card-body o_${moduleName}_chart">
                    <canvas t-ref="this.canvas"/>
                </div>
            </div>
        </div>
    </t>
</templates>`;

        const clientActionScss = `.o_${moduleName}_dashboard {
    .o_${moduleName}_chart {
        position: relative;
        height: 400px;
    }
}
`;

        const files = {
            "__init__.py": `# -*- coding: utf-8 -*-
from . import models, controllers`,
            "__manifest__.py": manifestContent,
            "models/__init__.py": `# -*- coding: utf-8 -*-
from . import ${formattedModelName}`,
            "controllers/__init__.py": `# -*- coding: utf-8 -*-
from . import main`,
            ["controllers/main.py"]: controllerPy,
            [`models/${formattedModelName}.py`]: modelPy,
            [`views/${formattedModelName}_views.xml`]: viewXml,
            "security/ir.access.csv": accessCsv,
            "data/ir_sequence_data.xml": sequenceXml,
            ["static/src/js/client_action.js"]: clientAction,
            ["static/src/xml/client_action.xml"]: clientActionTemplate,
            ["static/src/scss/client_action.scss"]: clientActionScss,
            [`demo/${moduleName}_data.xml`]: dataXml,
            "data/ir_cron_data.xml": cronXml,
        };

        const dirPromises = folders.map(dir =>
            vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(rootUri, dir))
        );

        const filePromises = Object.entries(files).map(([relPath, content]) => {
            const fileUri = vscode.Uri.joinPath(rootUri, relPath);
            const uint8arr = Buffer.from(content, 'utf8');
            return vscode.workspace.fs.writeFile(fileUri, uint8arr);
        });

        await Promise.all([...dirPromises, ...filePromises]);
    } else if (type == 'website_theme') {
        const folders = ['views'];

        const manifestContent = `# -*- coding: utf-8 -*-
{
    "name": "${displayName}",
    "version": "20.0.1.0.0",
    "category": "Theme",
    "summary": "Auto-generated Website Theme",
    "description": "This is an autogenerated website theme module scaffold.",
    "author": 'Your Company',
    "maintainer": "",
    "website": 'https://www.yourcompany.com',
    "depends": ["website"],
    "data": [
        "views/layout_template_views.xml",
        "views/header_template_views.xml",
        "views/footer_template_views.xml"
    ],
    "assets": {
        "web._assets_primary_variables": [],
        "web.assets_frontend": []
    },
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": False
}`;

        const layoutTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <template id="${moduleName}_homepage" inherit_id="website.homepage">
        <xpath expr="//*[@id='wrap']" position="replace">
            <div id="wrap" class="oe_structure">
                <section class="d-flex align-items-center justify-content-center" style="min-height: 50vh;">
                    <div class="container">
                        <div class="row justify-content-center text-center">
                            <div class="col-lg-8">
                                <h2 class="display-3 mb-4">Welcome to <b>Homepage</b>!</h2>
                                <p class="lead">Start building your theme</p>
                            </div>
                        </div>
                    </div>
                </section>
            </div>
        </xpath>
    </template>
</odoo>`;

        const headerTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <template id="${moduleName}_header" inherit_id="website.layout" name="${displayName} Header">
        <xpath expr="//header" position="replace">
            <header class="py-3 bg-light">
                <div class="container">
                    <div class="row align-items-center">
                        <div class="col-12 col-md-4 text-md-start text-center mb-2 mb-md-0">
                            <h1 class="h3 m-0 fw-bold">${displayName}</h1>
                        </div>
                        <div class="col-12 col-md-4 text-center mb-2 mb-md-0">
                            <ul class="nav justify-content-center">
                                <li class="nav-item"><a class="nav-link" href="/">Home</a></li>
                                <li class="nav-item"><a class="nav-link" href="/aboutus">About</a></li>
                                <li class="nav-item"><a class="nav-link" href="/contactus">Contact</a></li>
                            </ul>
                        </div>
                        <div class="col-12 col-md-4 text-end d-none d-md-block"/>
                    </div>
                </div>
            </header>
        </xpath>
    </template>
</odoo>`;

        const footerTemplate = `<?xml version="1.0" encoding="UTF-8"?>
<odoo>
    <template id="${moduleName}_footer" inherit_id="web.frontend_layout">
        <xpath expr="//footer[@id='bottom']" position="replace">
            <footer id="bottom" class="bg-dark text-white o_footer_custom">
                <div class="container py-4">
                    <div class="row">
                        <div class="col-md-6">
                            <h5>Custom Footer Title</h5>
                            <p>Your custom footer content goes here.</p>
                        </div>
                        <div class="col-md-6 text-end">
                            <p> <span t-field="res_company.name"/> - All rights reserved.</p>
                        </div>
                    </div>
                </div>
            </footer>
        </xpath>
    </template>
</odoo>`;

        const files = {
            "__init__.py": `# -*- coding: utf-8 -*-`,
            "__manifest__.py": manifestContent,
            "views/layout_template_views.xml": layoutTemplate,
            "views/header_template_views.xml": headerTemplate,
            "views/footer_template_views.xml": footerTemplate,
        };

        const dirPromises = folders.map(dir =>
            vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(rootUri, dir))
        );

        const filePromises = Object.entries(files).map(([relPath, content]) => {
            const fileUri = vscode.Uri.joinPath(rootUri, relPath);
            const uint8arr = Buffer.from(content, 'utf8');
            return vscode.workspace.fs.writeFile(fileUri, uint8arr);
        });

        await Promise.all([...dirPromises, ...filePromises]);
    }
    else if (type == 'systray_module') {
        const folders = ['static'];

        const manifestContent = `# -*- coding: utf-8 -*-
{
    "name": "${displayName}",
    "version": "20.0.1.0.0",
    "category": "Tools",
    "summary": "Auto-generated module",
    "description": "",
    "author": "",
    "maintainer": "",
    "website": "",
    "depends": ["base", "web"],
    "data": [],
    'assets': {
        'web.assets_backend': [
            '${moduleName}/static/src/js/systray.js',
            '${moduleName}/static/src/xml/systray_templates.xml',
        ],
    },
    "license": "LGPL-3",
    "installable": True,
    "auto_install": False,
    "application": True
    }`;

        const systrayJS = `import { Component } from "@odoo/owl";
import { registry } from "@web/core/registry";
import { useService } from "@web/core/utils/hooks";

export class SystrayIcon extends Component {
    static template = "${moduleName}.SystrayIcon";

    setup() {
        this.notification = useService("notification");
    }

    showNotification() {
        this.notification.add("Hello! This is a notification", {
            title: "Systray Notification",
            type: "info",
        });
    }
}

export const systrayItem = {
    Component: SystrayIcon,
};

registry.category("systray").add("${moduleName}.SystrayIcon", systrayItem, { sequence: 1 });
`;

        const systrayXML = `<?xml version="1.0" encoding="UTF-8" ?>
<templates xml:space="preserve">
    <t t-name="${moduleName}.SystrayIcon">
        <button type="button" class="btn btn-link o_nav_entry" title="My Custom Icon" t-on-click="() => this.showNotification()">
            <i class="oi" data-icon="star" role="img" aria-label="My Custom Icon"/>
        </button>
    </t>
</templates>`;

        const files = {
            '__init__.py': '',
            '__manifest__.py': manifestContent,
            [`static/src/js/systray.js`]: systrayJS,
            [`static/src/xml/systray_templates.xml`]: systrayXML,
        };

        const dirPromises = folders.map(dir =>
            vscode.workspace.fs.createDirectory(vscode.Uri.joinPath(rootUri, dir))
        );

        const filePromises = Object.entries(files).map(([relPath, content]) => {
            const fileUri = vscode.Uri.joinPath(rootUri, relPath);
            const uint8arr = Buffer.from(content, 'utf8');
            return vscode.workspace.fs.writeFile(fileUri, uint8arr);
        });

        await Promise.all([...dirPromises, ...filePromises]);
    }
}




